### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [zahmryan/project-5#1]
It doesn't look like this repo actually contains any updated code to meet [these project criteria](http://codekwondo.herokuapp.com/showcases/309). Are you sure you [committed your changes and pushed them up](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/git/committing_changes_to_git_and_pushing_to_github_and_heroku.md)?

**Comment by zahmryan** [comment]
Oops, just forgot to commit before pushing. Fixed now!

**Comment by chrisvfritz** [comment]
It looks like the app is [throwing an HTML error](http://validator.w3.org/check?uri=https%3A%2F%2Fmurmuring-chamber-7733.herokuapp.com%2F&charset=%28detect+automatically%29&doctype=Inline&group=0), since there's no doctype declaration or html and head tags. Can you fix this an update the repo?

**Comment by zahmryan** [comment]
should be fixed, validator test now passes

**Comment by chrisvfritz** [comment]
:+1: Looks much better. 

## Points of improvement for future projects

### Inconsistent indentation

I do notice some inconsistent indentation in some files, which I'd like you to try to clean up in future projects. Let me know if you're not sure what I mean or how you'd fix it.

### Ruby indentation

The standard indentation for Ruby (`.rb`) files is actually with two-space soft-tabs rather than hard-tabs. See if you can update your text editor to use two-space soft-tabs for all Ruby files. If you have trouble figuring it out, [this page may be helpful](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md). If it's not, just let me know and I'll be happy to point you in the right direction.
